create extension if not exists "http" with schema "extensions";

create extension if not exists "pg_cron" with schema "extensions";

create extension if not exists "vector" with schema "extensions";


drop trigger if exists "to_handled" on "public"."raw_data";

drop trigger if exists "to_text_database" on "public"."bodhi_raw_assets";

create table "public"."bodhi_indexer" (
    "id" bigint generated by default as identity not null,
    "index" bigint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."bodhi_indexer" enable row level security;

create table "public"."bodhi_text_assets_k_v" (
    "id" bigint generated by default as identity not null,
    "data" text,
    "metadata" json,
    "created_at" timestamp with time zone not null default now(),
    "if_vectored" boolean default false,
    "uuid" text,
    "embedding" vector(1536),
    "creator" text,
    "id_on_chain" bigint
);


alter table "public"."bodhi_text_assets_k_v" enable row level security;

alter table "public"."bodhi_text_assets" drop column "if_sliced";

alter table "public"."bodhi_text_assets" add column "if_to_text_assets_k_v" boolean default false;

CREATE UNIQUE INDEX bodhi_indexer_pkey ON public.bodhi_indexer USING btree (id);

CREATE UNIQUE INDEX bodhi_text_assets_k_v_pkey ON public.bodhi_text_assets_k_v USING btree (id);

alter table "public"."bodhi_indexer" add constraint "bodhi_indexer_pkey" PRIMARY KEY using index "bodhi_indexer_pkey";

alter table "public"."bodhi_text_assets_k_v" add constraint "bodhi_text_assets_k_v_pkey" PRIMARY KEY using index "bodhi_text_assets_k_v_pkey";

CREATE TRIGGER to_k_v AFTER INSERT ON public.bodhi_text_assets FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://jzwizjgzaxdaatskzsih.supabase.co/functions/v1/to_bodhi_text_assets_k_v', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d2l6amd6YXhkYWF0c2t6c2loIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMjYwNTA3NiwiZXhwIjoyMDE4MTgxMDc2fQ.qSYWQCX-BsTzpew3Lv3HMfRyzqo-1RXRj0zmRMrVCo8"}', '{}', '1000');

CREATE TRIGGER to_text_database AFTER INSERT ON public.bodhi_raw_assets FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://jzwizjgzaxdaatskzsih.supabase.co/functions/v1/to_text_database', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d2l6amd6YXhkYWF0c2t6c2loIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMjYwNTA3NiwiZXhwIjoyMDE4MTgxMDc2fQ.qSYWQCX-BsTzpew3Lv3HMfRyzqo-1RXRj0zmRMrVCo8"}', '{}', '1000');


